'use client';

import { useRef, useState } from 'react';
import { StructuredReport } from '@/types/reports';
import { ReportRenderer } from './ReportRenderer';
import { Button } from '@/components/ui/button';
import { Dumbbell, Image, Printer, Copy, Loader2 } from 'lucide-react';
import { format } from 'date-fns';
import { toPng } from 'html-to-image';
import { toast } from 'sonner';

interface ReportContainerProps {
  report: StructuredReport;
  userName: string;
}

export function ReportContainer({ report, userName }: ReportContainerProps) {
  const reportRef = useRef<HTMLDivElement>(null);
  const [exporting, setExporting] = useState(false);

  const handleExportImage = async () => {
    if (!reportRef.current) return;

    setExporting(true);
    try {
      // Check if dark mode is active
      const isDarkMode = document.documentElement.classList.contains('dark');

      const dataUrl = await toPng(reportRef.current, {
        quality: 1,
        pixelRatio: 2,
        backgroundColor: isDarkMode ? '#0f172a' : '#ffffff',
      });

      const link = document.createElement('a');
      link.download = `CoachTrack-${report.title.replace(/[^a-z0-9]/gi, '-')}-${format(new Date(), 'yyyy-MM-dd')}.png`;
      link.href = dataUrl;
      link.click();

      toast.success('Report saved as image');
    } catch (error) {
      toast.error('Failed to export image');
    } finally {
      setExporting(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopyToClipboard = async () => {
    const textContent = `
${report.title}
${report.subtitle || ''}
${report.dateRange || ''}
${'-'.repeat(50)}

${report.sections
  .map((section) => {
    if (section.type === 'text') return section.content;
    if (section.type === 'highlight') return `⭐ ${section.content}`;
    if (section.type === 'pr') return `🏆 ${section.exercise}: ${section.value}`;
    return '';
  })
  .filter(Boolean)
  .join('\n\n')}

${report.summary || ''}
${report.footer || ''}

Generated by CoachTrack - ${format(new Date(), 'MMMM d, yyyy')}
    `.trim();

    try {
      await navigator.clipboard.writeText(textContent);
      toast.success('Report copied to clipboard');
    } catch (error) {
      toast.error('Failed to copy to clipboard');
    }
  };

  return (
    <div>
      {/* Export Controls - Hide on print */}
      <div className="flex items-center justify-end gap-2 mb-6 print:hidden">
        <Button
          variant="outline"
          size="sm"
          onClick={handleCopyToClipboard}
        >
          <Copy className="h-4 w-4 mr-2" />
          Copy
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={handleExportImage}
          disabled={exporting}
        >
          {exporting ? (
            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
          ) : (
            <Image className="h-4 w-4 mr-2" />
          )}
          Save PNG
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={handlePrint}
        >
          <Printer className="h-4 w-4 mr-2" />
          Print
        </Button>
      </div>

      {/* Report Content */}
      <div
        ref={reportRef}
        data-report-container
        className="bg-gradient-to-br from-slate-50 to-white dark:from-slate-950 dark:to-slate-900 text-slate-900 dark:text-slate-100 p-8 rounded-xl border border-slate-200 dark:border-slate-800 shadow-lg print:shadow-none print:border-0"
      >
        {/* Header with CoachTrack Branding */}
        <div className="border-b-2 border-primary pb-6 mb-8">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="h-12 w-12 rounded-xl bg-gradient-to-br from-blue-600 to-cyan-500 flex items-center justify-center shadow-lg">
                <Dumbbell className="h-6 w-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold bg-gradient-to-r from-blue-600 to-cyan-500 bg-clip-text text-transparent">
                  CoachTrack
                </h1>
                <p className="text-sm text-slate-500 dark:text-slate-400">
                  {report.reportType.charAt(0).toUpperCase() + report.reportType.slice(1)} Report
                </p>
              </div>
            </div>
            <div className="text-right text-sm text-slate-500 dark:text-slate-400">
              <p className="font-medium text-slate-700 dark:text-slate-300">{userName}</p>
              <p>{format(new Date(), 'MMMM d, yyyy')}</p>
            </div>
          </div>
        </div>

        {/* Report Title */}
        <div className="mb-8">
          <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100 mb-2">
            {report.title}
          </h2>
          {report.subtitle && (
            <p className="text-lg text-slate-600 dark:text-slate-400">
              {report.subtitle}
            </p>
          )}
          {report.dateRange && (
            <p className="text-sm text-slate-500 dark:text-slate-500 mt-1">
              {report.dateRange}
            </p>
          )}
        </div>

        {/* Report Sections */}
        <ReportRenderer sections={report.sections} />

        {/* Summary */}
        {report.summary && (
          <div className="mt-8 pt-6 border-t border-slate-200 dark:border-slate-800">
            <h3 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mb-3">
              Summary
            </h3>
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
              {report.summary}
            </p>
          </div>
        )}

        {/* Footer */}
        <div className="mt-12 pt-6 border-t border-slate-200 dark:border-slate-800 text-center">
          <p className="text-xs text-slate-400 dark:text-slate-600">
            {report.footer || `Generated by CoachTrack | ${format(new Date(), 'MMMM d, yyyy \'at\' h:mm a')}`}
          </p>
        </div>
      </div>
    </div>
  );
}
